name: docker-build

on:
  push:
#    branches: ['main']
    tags:
      - release-**

env:
  DOCKER_IMAGE: ghcr.io/min010324/devkor-bestudy
  DOCKER_CONTAINER: devkor-bestudy-test

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Docker
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.BESTUDY_GIT_TOKEN}}

      - name: build and push image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_IMAGE}}:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: setup .env
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT}}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS}}" >> .env
          echo "DB_USER=${{ secrets.DB_USER}}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE}}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY}}" >> .env
          echo "MAIL_USER=${{ secrets.MAIL_USER}}" >> .env
          echo "MAIL_PASS=${{ secrets.MAIL_PASS}}" >> .env
          echo "ACCESS_TOKEN_SECRET_KEY=${{ secrets.ACCESS_TOKEN_SECRET_KEY}}" >> .env
          echo "REFRESH_TOKEN_SECRET_KEY=${{ secrets.REFRESH_TOKEN_SECRET_KEY}}" >> .env
          echo "ACCESS_TOKEN_EXPIRE_TIME=${{ secrets.ACCESS_TOKEN_EXPIRE_TIME}}" >> .env
          echo "REFRESH_TOKEN_EXPIRE_TIME=${{ secrets.REFRESH_TOKEN_EXPIRE_TIME}}" >> .env
          echo "HASH_SALT=${{ secrets.HASH_SALT}}" >> .env

          cat .env
      - name: Run Docker
        run: |
          docker stop ${{env.DOCKER_CONTAINER}} && docker rm ${{env.DOCKER_CONTAINER}} && docker rmi ${{env.DOCKER_IMAGE}}:latest
          docker run --env-file ./.env --platform linux/amd64 -d --name ${{env.DOCKER_CONTAINER}} --network host --restart always ${{env.DOCKER_IMAGE}}:latest
